export enum ActionTypes {
  SET_AUTHORIZED = 'SET_AUTHORIZED',
  SET_UNAUTHORIZED = 'SET_UNAUTHORIZED',
  SET_AUTH_LOADING = 'SET_AUTH_LOADING',
  SET_AUTH_PASSWORD_ERROR = 'SET_AUTH_PASSWORD_ERROR'
}

export default ActionTypes;
